import React from 'react';
import TvSeries from '../../components/TvSeries';
import Head from 'next/head';

function Tv({ tvData }) {

  return (
    <>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TvSeries tvdata={tvData} />
    </>

  )
}

export async function getServerSideProps() {
  // Fetch data from external API

  const tv = await fetch(
    `https://api.themoviedb.org/3/tv/popular?api_key=02873dc6fd43867b5f26c4204ab6a508&language=en-US&page=1`);
  const tvData = await tv.json();

  ;

  // Pass data to the page via props
  return { props: { tvData } }
}

export default Tv