import React from 'react';
import BackToHome from '../../components/BackToHome';
import Head from 'next/head';

function About() {
  return (
    <>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <BackToHome/>
     <div className='flex flex-col justify-center items-center mx-auto bg-[#371B58] hover:scale-110 transition-all duration-700 p-12 rounded-xl w-2/3'>
      <h1 className='text-4xl font-bold text-[#fff]'>It is my first NextJs project</h1>
      <p className='text-2xl font-semibold text-[#999] w-2/3 my-12 font-mono'>It is not a serious movie site. Only such a experiment and practice for me to learn how to works NextJs routing and to deepen my Tailwind knowledge. I think this is a small step for humanity but a big step for me :)
      </p>
      </div>
    </>
   
  )
}

export default About