import Head from 'next/head';
import Movie from '../components/Movie';
import Nav from '../components/nav';



export default function Home({data}) {
  
  return (
    <div className="">
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Nav/>

    <main className='flex'>
      
      <Movie data={data} />
      
     
    </main>
      
    </div>
  )
}
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`
  https://api.themoviedb.org/3/movie/top_rated?api_key=02873dc6fd43867b5f26c4204ab6a508&language=en-US&page=1`)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}
