import Head from 'next/head';
import Movie from '../components/Movie';
import Nav from '../components/nav';


export default function Home() {

  
  return (
    <div className="">
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Nav/>

    <main>
      
      <Movie/>
      
     
    </main>
      
    </div>
  )
}
